# Generated by Django 5.2.6 on 2025-09-22 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventInfo',
            fields=[
                ('EventInfoUserId', models.AutoField(primary_key=True, serialize=False)),
                ('EventInfoRequestId', models.BigIntegerField()),
                ('EventInfoAnswerId', models.BigIntegerField()),
                ('PhotoFileName', models.CharField(max_length=500)),
                ('PlantType', models.CharField(max_length=500)),
                ('EventPrediction', models.CharField(max_length=10000)),
            ],
        ),
    ]
