# Generated by Django 5.2.6 on 2025-09-22 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('event_id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('tree_type', models.CharField(max_length=500)),
                ('has_cracks', models.IntegerField()),
                ('has_hollows', models.IntegerField()),
                ('has_fruits_or_flowers', models.IntegerField()),
                ('injuries', models.CharField(max_length=500)),
                ('photo_file_name', models.CharField(max_length=500)),
                ('answer', models.CharField(max_length=10000)),
            ],
        ),
        migrations.DeleteModel(
            name='EventInfo',
        ),
    ]
