# Generated by Django 5.2.6 on 2025-09-23 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_application_rename_info_result'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Application',
        ),
    ]
