# Generated by Django 5.2.6 on 2025-09-25 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_photo_result_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='photo',
            name='user_id',
            field=models.CharField(default='egor', max_length=500),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='photo',
            name='image',
            field=models.ImageField(default='test', upload_to='photos/'),
            preserve_default=False,
        ),
    ]
