# Generated by Django 5.2.6 on 2025-09-25 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_rename_name_photo_title_photo_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='created_at',
        ),
    ]
