# Generated by Django 5.2.6 on 2025-09-29 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_photo_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='url',
            field=models.CharField(default='test', max_length=500),
            preserve_default=False,
        ),
    ]
